@host = http://localhost:8080
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlhdCI6MTc2NzA0NDI1OCwiZXhwIjoxNzY3MDQ0NTU4fQ.EBOQZnLsLRhSiAt05_tQpEDg4BXVq8If8BiF2HwM-7s
@refreshToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzY3MDQ0MjMxLCJleHAiOjE3NjcwNDYwMzF9.jmMwA8QusMXr0tF4xFruvpDzpEMEuA_hXfETSXdFh8A
@newAccessToken =

### 회원가입
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "1234",
  "nickname": "테스트유저1",
  "province": "서울시",
  "city": "강남구",
  "town": "신사동"
}

### 로그인
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "1234"
}

### AccessToken 재발급
POST http://localhost:8080/api/users/token/reissue
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### API 호출 (AccessToken 필요)
GET {{host}}/api/test/auth
Authorization: Bearer {{accessToken}}

### API 재호출 (재발급된 AccessToken)
GET {{host}}/api/test/auth
Authorization: Bearer {{newAccessToken}}


