@host = http://localhost:8080
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlhdCI6MTc2NzMyMTQ5NCwiZXhwIjoxNzY3MzIxNzk0fQ.pBhsD9LnCgSa8uo2ZB6eHXHDYc2bUxh1ZmcofKayxmA
@refreshToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzY3MzIyMDgwLCJleHAiOjE3NjczMjM4ODB9.EKjdG3kTvPYlphCGF8acZj0fbfAw2BLKlPd-dBA7gTE
@newAccessToken =
@masterToken = 19970111

### 회원가입
POST {{host}}/api/users/signup
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "1234",
  "nickname": "테스트유저1",
  "province": "서울시",
  "city": "강남구"
}

### 로그인: AT는 Body, RT는 Set-Cookie + DB 저장
POST {{host}}/api/users/login
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "1234"
}

> {%
    const token = response.body?.data?.accessToken;
    client.global.set("accessToken", token);
%}


### AccessToken 재발급
POST {{host}}/api/users/token/reissue
Cookie: refreshToken={{refreshToken}}

{
  "refreshToken": "{{refreshToken}}"
}

### API 호출 (AccessToken 필요)
GET {{host}}/api/test/auth
Authorization: Bearer {{accessToken}}

### API 재호출 (재발급된 AccessToken)
GET {{host}}/api/test/auth
Authorization: Bearer {{newAccessToken}}

### 로그아웃: RT DB 삭제 + 쿠키 삭제(Set-Cookie 만료)
POST {{host}}/api/users/logout
Cookie: refreshToken={{refreshToken}}

### 마스터 토큰으로 API 호출 (만료/검증 안함)
GET {{host}}/api/test/auth
Authorization: Bearer {{masterToken}}

